### ISSUE TITLE
Make file name in header editable

### ISSUE THREAD

**Issue by annplaksin** [Signature-Sound-Vienna/mei-friend-online#4]
**Is your feature request related to a problem? Please describe.**
When editing a file, or esp. copy-paste code into mei-friend for refining, the filename of a downloaded file won't change.

![grafik](https://user-images.githubusercontent.com/12529090/190389136-d5eed704-4e0d-4859-be17-ef10d2646232.png)

**Describe the solution you'd like**
Make the file name editable to download a file with its new file name

**Comment by musicog** [comment]
Now implemented when working locally (via 'open file' or through drag'n'drop) - not implemented working from a URL (where we can't assume write access to change a filename), nor when working from a GitHub repository (where a separate rename-to-create-a-new-file functionality already exists in the commit menu).

I've introduced some styling to differentiate 'editable' (working locally) and 'non-editable' (not working locally).

Currently available to test at https://repo.mdw.ac.at/mei-friend.

Closing issue for now as implemented per the above, but feel free to reopen for feedback!
And thanks very much for the suggestion :-)
